/**
 * Map Data Service for Islamabad & Rawalpindi Hospitals
 */

export const islamabadRawalpindiHospitals = [
  {
    id: 'hosp-1',
    name: 'Shifa International Hospital',
    city: 'Islamabad',
    area: 'Sector H-8/4',
    lat: 33.6823,
    lng: 73.0664,
    phone: '+92 51 8463666',
    emergencyPhone: '1122',
    rating: 4.8,
    erAvailable: true,
    icuBeds: 42,
    specialties: ['Cardiology', 'Neurology', 'Oncology', 'Organ Transplant'],
    address: 'Pitras Bukhari Rd, H-8/4 H 8/4 H-8, Islamabad',
    gmapUrl: 'https://maps.google.com/?q=Shifa+International+Hospital+Islamabad',
    type: 'Tertiary Care Hospital',
  },
  {
    id: 'hosp-2',
    name: 'PIMS (Pakistan Institute of Medical Sciences)',
    city: 'Islamabad',
    area: 'Sector G-8/3',
    lat: 33.6938,
    lng: 73.0551,
    phone: '+92 51 9261170',
    emergencyPhone: '1122',
    rating: 4.6,
    erAvailable: true,
    icuBeds: 60,
    specialties: ['Trauma Center', 'Burn Center', 'Pediatrics', 'Neurosurgery'],
    address: 'Ibn-e-Sina Rd, G-8/3 G-8, Islamabad',
    gmapUrl: 'https://maps.google.com/?q=Pakistan+Institute+of+Medical+Sciences+PIMS+Islamabad',
    type: 'Public Government Hospital',
  },
  {
    id: 'hosp-3',
    name: 'Maroof International Hospital',
    city: 'Islamabad',
    area: 'Sector F-10 Markaz',
    lat: 33.6963,
    lng: 73.0116,
    phone: '+92 51 2222920',
    emergencyPhone: '+92 51 2222920',
    rating: 4.7,
    erAvailable: true,
    icuBeds: 18,
    specialties: ['Orthopedics', 'Gynecology', 'General Surgery', 'Cardiology'],
    address: '10th Ave, F-10 Markaz, Islamabad',
    gmapUrl: 'https://maps.google.com/?q=Maroof+International+Hospital+Islamabad',
    type: 'Private General Hospital',
  },
  {
    id: 'hosp-4',
    name: 'Kulsum International Hospital',
    city: 'Islamabad',
    area: 'Blue Area',
    lat: 33.7142,
    lng: 73.0617,
    phone: '+92 51 8446666',
    emergencyPhone: '+92 51 8446666',
    rating: 4.5,
    erAvailable: true,
    icuBeds: 15,
    specialties: ['Cardiac Care', 'Internal Medicine', 'Diagnostic Imaging'],
    address: 'Kulsum Plaza, 2010 Jinnah Ave, Blue Area, Islamabad',
    gmapUrl: 'https://maps.google.com/?q=Kulsum+International+Hospital+Islamabad',
    type: 'Private Cardiac & Care Hospital',
  },
  {
    id: 'hosp-5',
    name: 'Holy Family Hospital',
    city: 'Rawalpindi',
    area: 'Satellite Town',
    lat: 33.6331,
    lng: 73.0715,
    phone: '+92 51 9290321',
    emergencyPhone: '1122',
    rating: 4.4,
    erAvailable: true,
    icuBeds: 35,
    specialties: ['Maternal & Child Health', 'Gastroenterology', 'Urology'],
    address: 'Holy Family Rd, Satellite Town, Rawalpindi',
    gmapUrl: 'https://maps.google.com/?q=Holy+Family+Hospital+Rawalpindi',
    type: 'Teaching Hospital',
  },
  {
    id: 'hosp-6',
    name: 'Combined Military Hospital (CMH)',
    city: 'Rawalpindi',
    area: 'Cantt',
    lat: 33.5936,
    lng: 73.0526,
    phone: '+92 51 5613000',
    emergencyPhone: '+92 51 5613000',
    rating: 4.9,
    erAvailable: true,
    icuBeds: 50,
    specialties: ['Trauma', 'Advanced Surgery', 'Rehabilitation', 'Burn Unit'],
    address: 'Tamizuddin Rd, Lalkurti, Cantt, Rawalpindi',
    gmapUrl: 'https://maps.google.com/?q=CMH+Rawalpindi',
    type: 'Military Tertiary Care Hospital',
  },
  {
    id: 'hosp-7',
    name: 'Benazir Bhutto Hospital (DHQ)',
    city: 'Rawalpindi',
    area: 'Murree Road',
    lat: 33.6192,
    lng: 73.0674,
    phone: '+92 51 9290301',
    emergencyPhone: '1122',
    rating: 4.3,
    erAvailable: true,
    icuBeds: 30,
    specialties: ['Emergency Medicine', 'General Medicine', 'ENT'],
    address: 'Murree Rd, Chandni Chowk, Rawalpindi',
    gmapUrl: 'https://maps.google.com/?q=Benazir+Bhutto+Hospital+Rawalpindi',
    type: 'District Headquarter Hospital',
  },
  {
    id: 'hosp-8',
    name: 'Quaid-e-Azam International Hospital',
    city: 'Rawalpindi / Islamabad Border',
    area: 'Peshawar Road',
    lat: 33.6264,
    lng: 72.9691,
    phone: '+92 51 8449100',
    emergencyPhone: '+92 51 8449100',
    rating: 4.8,
    erAvailable: true,
    icuBeds: 40,
    specialties: ['Cardiovascular', 'Nephrology & Dialysis', 'Pulmonology'],
    address: 'Near Golra Morr, Peshawar Rd, Rawalpindi',
    gmapUrl: 'https://maps.google.com/?q=Quaid-e-Azam+International+Hospital+Islamabad',
    type: 'Multi-Specialty Medical Complex',
  },
];
