export const languages = [
  { code: 'en-US', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'ur-PK', name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
  { code: 'pa-PK', name: 'Punjabi', native: 'پنجابی', flag: '🇵🇰' },
  { code: 'ps-AF', name: 'Pashto', native: 'پښتو', flag: '🇵🇰' },
  { code: 'sd-PK', name: 'Sindhi', native: 'سنڌي', flag: '🇵🇰' },
  { code: 'zh-CN', name: 'Chinese', native: '中文', flag: '🇨🇳' },
];

export const translations = {
  'en-US': {
    appName: 'LifeLine',
    tagline: 'Your AI-Powered Emergency & Healthcare Companion',
    listening: 'Listening... Speak now',
    speakPrompt: 'Press mic and ask anything (e.g., "Find cardiology clinic near Islamabad")',
    voiceAssistant: 'LifeLine Voice Assistant',
    selectLanguage: 'Select Language',
    welcomeBack: 'Welcome back,',
    emergencyHeader: 'Medical Emergency?',
    callAmbulance: 'Call Ambulance (1122)',
    quickTriage: 'Quick Body Triage',
    bodyTriageDesc: 'Tap anatomical zones to connect with relevant specialists.',
    findHospitals: 'Islamabad & Rawalpindi Hospitals',
    aiScan: 'AI Vision Triage',
    ocrVault: 'Lab Document OCR',
    drugChecker: 'Drug Interaction Checker',
    emergencyQR: 'Emergency Medical QR',
    reminders: 'Smart Pill Reminders',
    moodJournal: 'Daily Mood Tracker',
    replayIntro: 'Replay ECG Intro',
    front: 'Front View',
    back: 'Back View',
    emergencyContact: 'Emergency Contact',
    bloodType: 'Blood Type',
    allergies: 'Allergies',
    chronicConditions: 'Chronic Conditions',
    activeMeds: 'Active Medications',
    readAloud: 'Read Aloud (TTS)',
    analyzing: 'Analyzing medical image...',
    scanReady: 'AI Triage Complete',
  },
  'ur-PK': {
    appName: 'لائف لائن',
    tagline: 'آپ کا ذہین طبی اور ایمرجنسی معاون',
    listening: 'سن رہا ہے... بولیں',
    speakPrompt: 'مائیک پر ٹیپ کریں اور بات کریں (مثال: اسلام آباد میں ہسپتال تلاش کریں)',
    voiceAssistant: 'لائف لائن وائس اسسٹنٹ',
    selectLanguage: 'زبان منتخب کریں',
    welcomeBack: 'خوش آمدید،',
    emergencyHeader: 'طبی ہنگامی صورتحال؟',
    callAmbulance: 'ایمبولینس کو کال کریں (1122)',
    quickTriage: 'جسمانی اعضاء کا علاج',
    bodyTriageDesc: 'متعلقہ ماہرین سے رابطہ کرنے کے لیے جسم کے حصے پر کلک کریں۔',
    findHospitals: 'اسلام آباد اور راولپنڈی کے ہسپتال',
    aiScan: 'مصنوعی ذہانت سے معائنہ',
    ocrVault: 'لیب رپورٹ سکینر',
    drugChecker: 'ادویات کے باہمی اثرات کی جانچ',
    emergencyQR: 'ایمرجنسی میڈیکل کیو آر',
    reminders: 'ادویات کی یاد دہانی',
    moodJournal: 'روزانہ کا موڈ ٹریکر',
    replayIntro: 'ای سی جی انٹرو دوبارہ چلائیں',
    front: 'سامنے کا منظر',
    back: 'پشت کا منظر',
    emergencyContact: 'ہنگامی رابطہ',
    bloodType: 'بلڈ گروپ',
    allergies: 'ایلرجی',
    chronicConditions: 'دائمی بیماری',
    activeMeds: 'موجودہ ادویات',
    readAloud: 'آواز میں سنیں',
    analyzing: 'تصویر کا تجزیہ ہو رہا ہے...',
    scanReady: 'تجزیہ مکمل ہو گیا',
  },
  'pa-PK': {
    appName: 'لائف لائن',
    tagline: 'تہاڈا اپنا عقل مند صحت دا ساتھی',
    listening: 'سن رہیا اے... بولو',
    speakPrompt: 'مائیک دباؤ تے بولو (مثال: راولپنڈی میں ڈاکٹر لبھو)',
    voiceAssistant: 'لائف لائن آواز اسسٹنٹ',
    selectLanguage: 'زبان چنو',
    welcomeBack: 'جی آیاں نوں،',
    emergencyHeader: 'کوئی ہنگامی مسئلہ؟',
    callAmbulance: 'ایمبولینس منگواؤ (1122)',
    quickTriage: 'جسمانی حصیاں دی جانچ',
    bodyTriageDesc: 'ڈاکٹر لبھن لئی جسم دے حصے تے کلک کرو۔',
    findHospitals: 'اسلام آباد تے راولپنڈی دے ہسپتال',
    aiScan: 'AI میڈیکل سکین',
    ocrVault: 'رپورٹ پڑھن والا سکینر',
    drugChecker: 'دوائیاں دا ٹکراؤ چیک کرو',
    emergencyQR: 'ایمرجنسی QR کوڈ',
    reminders: 'دوائی دا ٹائم یاد دہانی',
    moodJournal: 'روزانہ موڈ ٹریکر',
    replayIntro: 'ECG اینیمیشن دیکھو',
    front: 'اگلا پاسہ',
    back: 'پچھلا پاسہ',
    emergencyContact: 'ہنگامی نمبر',
    bloodType: 'بلڈ گروپ',
    allergies: 'ایلرجیاں',
    chronicConditions: 'پرانیاں بیماریاں',
    activeMeds: 'چلدی دوائیاں',
    readAloud: 'آواز میں سنو',
    analyzing: 'جانچ ہو رہی اے...',
    scanReady: 'سکین مکمل',
  },
  'ps-AF': {
    appName: 'لائف لائن',
    tagline: 'ستاسو هوښیار طبي او بیړنی ملګری',
    listening: 'اوریدل کیږي... خبرې وکړئ',
    speakPrompt: 'مایک فشار ورکړئ او ووایاست',
    voiceAssistant: 'لائف لائن غږیز مرستیال',
    selectLanguage: 'ژبه غوره کړئ',
    welcomeBack: 'ښه راغلاست،',
    emergencyHeader: 'بيړني طبي حالت؟',
    callAmbulance: 'امبولانس ته زنګ ووهئ (1122)',
    quickTriage: 'د بدن د برخو معاینه',
    bodyTriageDesc: 'د ډاکټر موندلو لپاره د بدن په برخه کلیک وکړئ.',
    findHospitals: 'د اسلام اباد او راولپینډۍ روغتونونه',
    aiScan: 'د هوښیار معاینې سکین',
    ocrVault: 'د راپور سکینر',
    drugChecker: 'د درملو تداخل چک کړئ',
    emergencyQR: 'بیړنی QR کوډ',
    reminders: 'د درملو یادوونکی',
    moodJournal: 'ورځنی مزاج ټریکر',
    replayIntro: 'د ECG ننداره وګورئ',
    front: 'مخکینی لید',
    back: 'شاته لید',
    emergencyContact: 'بیړنۍ اړيکه',
    bloodType: 'د وینې ګروپ',
    allergies: 'الرژي',
    chronicConditions: 'مزمنې ناروغۍ',
    activeMeds: 'اوسني درمل',
    readAloud: 'په لوړ غږ اوریدل',
    analyzing: 'د عکس تحلیل روان دی...',
    scanReady: 'تحلیل بشپړ شو',
  },
  'sd-PK': {
    appName: 'لائف لائن',
    tagline: 'توهان جو ذهين طبي مددگار',
    listening: 'ٻڌي رهيو آهي... ڳالهايو',
    speakPrompt: 'مائيڪ تي ڪلڪ ڪريو ۽ ڳالهايو',
    voiceAssistant: 'لائف لائن وائس اسسٽنٽ',
    selectLanguage: 'ٻولي چونڊيو',
    welcomeBack: 'ڀلي ڪري آيا،',
    emergencyHeader: 'طبي هنگامي صورتحال؟',
    callAmbulance: 'ايمبولينس کي ڪال ڪريو (1122)',
    quickTriage: 'جسمن جي حصن جي چڪاس',
    bodyTriageDesc: 'ڊاڪٽر ڳولڻ لاءِ جسم جي حصي تي ڪلڪ ڪريو.',
    findHospitals: 'اسلام آباد ۽ راولپنڊي جا اسپتال',
    aiScan: 'مصنوعي ذهانت اسڪين',
    ocrVault: 'رپورٽ اسڪينر',
    drugChecker: 'دوائن جي اثرن جي چڪاس',
    emergencyQR: 'ايمرجنسي QR ڪوڊ',
    reminders: 'دوائن جي ياددهاني',
    moodJournal: 'روزاني موڊ ٽريڪر',
    replayIntro: 'ECG اينيميشن ڏسو',
    front: 'اڳيون پاسو',
    back: 'پويون پاسو',
    emergencyContact: 'هنگامي رابطو',
    bloodType: 'بلڈ گروپ',
    allergies: 'ايلرجي',
    chronicConditions: 'بيماريون',
    activeMeds: 'موجوده دوائون',
    readAloud: 'آواز ۾ ٻڌو',
    analyzing: 'تجزيي ٿي رهيو آهي...',
    scanReady: 'اسڪين مڪمل',
  },
  'zh-CN': {
    appName: 'LifeLine 生命线',
    tagline: '您的AI智能医疗与急救助手',
    listening: '正在聆听... 请说话',
    speakPrompt: '点击麦克风说话（例如："查找伊斯兰堡心血管诊所"）',
    voiceAssistant: 'LifeLine 语音助手',
    selectLanguage: '选择语言',
    welcomeBack: '欢迎回来，',
    emergencyHeader: '医疗紧急情况？',
    callAmbulance: '呼叫救护车 (1122)',
    quickTriage: '2D人体部位分诊',
    bodyTriageDesc: '点击人体部位快速查找对应专科医生。',
    findHospitals: '伊斯兰堡及拉瓦尔品第医院地图',
    aiScan: 'AI影像与伤口智能分诊',
    ocrVault: '化验单及病例识别 (OCR)',
    drugChecker: '药物相互作用筛查',
    emergencyQR: '急救医疗 QR 码',
    reminders: '智能服药提醒',
    moodJournal: '每日情绪与症状日志',
    replayIntro: '重播心电图动画',
    front: '人体正面',
    back: '人体背面',
    emergencyContact: '紧急联系人',
    bloodType: '血型',
    allergies: '过敏史',
    chronicConditions: '慢性病',
    activeMeds: '正在服用的药物',
    readAloud: '语音朗读 (TTS)',
    analyzing: '正在分析医疗图像...',
    scanReady: 'AI 分诊分析完成',
  }
};
